### ISSUE TITLE
Poll in static query job doesn't propagate kwargs

### ISSUE THREAD

**Issue by vishalkuo** [humio/python-humio#17]
**Describe the bug**
Currently, the `poll()` method in `StaticQueryJob` will [not propagate](https://github.com/humio/python-humio/blob/master/src/humiolib/QueryJob.py#L161) `**kwargs` meaning that if you set a timeout in the function call, it never gets set in the webcaller

**To Reproduce**
```python
query_job = client.create_queryjob(query)
query_job.poll(timeout=1) # can hang indefinitely 
```

**Expected behavior**
the above snippet should raise an exception

**Comment by AlexanderBrandborg** [comment]
Fixed by https://github.com/humio/python-humio/pull/18
